
name: Build and Deploy to Cloud Run

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  PROJECT_ID: new-project-366703
  GAR_LOCATION: asia-south1
  REPOSITORY_NAME: github-artifact
  BUCKET_NAME: dev.pocketalktest.ml
  REGION: asia-south1
  SERVICE: github

jobs:

  deploy:
    # Add 'id-token' with the intended permissions for workload identity federation
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Google Auth
        id: auth
        uses: 'google-github-actions/auth@v0'
        with:
          token_format: 'access_token'
          workload_identity_provider: projects/331230062057/locations/global/workloadIdentityPools/frontend-identity-pool/providers/frontend-identity-provider
          service_account:  frontend-build-deploy-sa@new-project-366703.iam.gserviceaccount.com
      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'
      - name: 'Use gcloud CLI'
        run: 'gcloud info'
      - name: Delet files from bucket
        run: gsutil rm gs://${BUCKET_NAME}/**
      - name: Upload Build File
        run: gsutil cp -r *.html gs://${BUCKET_NAME}


